### ISSUE TITLE
Dimensiones y responsive

### ISSUE THREAD

**Issue by fsica0308** [blas94/ENTREGABLE-Mercado-Liebre#1]
Hola! Te comento un par de cositas que vi. 
Lo primero seria revisar margin, padding y dimensiones para el responsive, ya que al disminuir el tamaño a tableta o inferiores, queda todo pegado a la derecha sin ningún tipo de separación. Por ultimo en las paginas login y register, queda todo arriba y un espacio blanco abajo, ahí podrías hacer que el footer quede pegado abajo, y agrandar los formularios y centrarlos, o bien simplemente poner el fondo gris. Fuera de eso la veo perfecta la pagina!

**Comment by blas94** [comment]
Dale, gracias por tomarte el tiempo de verlo, cuando llegue a casa lo veo.

**Comment by blas94** [comment]
Dale, gracias por tomarte el tiempo de verlo, cuando llegue a casa lo veo.
